version: '3'

services:
  laravel_practice_web:
    container_name: laravel_practice_web
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_practice_app

  laravel_practice_app:
    container_name: laravel_practice_app
    build: ./php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - laravel_practice_db

  laravel_practice_db:
    container_name: laravel_practice_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/etc/mysql/mysql.conf.d
      - laravel_practice_data:/var/lib/mysql

volumes:
  laravel_practice_data:
